name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-node-app .

      # You may need additional steps here to push the Docker image to a container registry

      - name: Extract build artifacts
        run: |
          docker run --rm my-node-app sh -c "cp -r /app /github/workspace"

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1
        with:
          args: deploy --prod --dir=app  # Replace 'app' with the directory containing your build artifacts
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN}}
