name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Replace with your build command if different

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1
        with:
          args: deploy --prod --dir=build  # Replace 'build' with the directory containing your build artifacts
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
